
# state management
remote_state {
  backend = "gcs"
  config = {
    bucket = "gman-tf-state-bucket-01"
    prefix = "terragrunt/state/${path_relative_to_include()}"
  }
}

locals {
  project_id = "angelic-digit-297517" 
  region     = "us-central1"
  zone    = "us-central1-a"
  tf_version = ">= 1.6.2"
  google_provider_version = ">= 6.35.0"
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt" # This will overwrite the file if it was previously generated by Terragrunt
  contents  = <<EOF
provider "google" {
  project = "${local.project_id}"
  region  = "${local.region}"
}

terraform {
  required_version = "${local.tf_version}"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "${local.google_provider_version}"
    }
  }
  backend "gcs" {}
}
EOF
}
