name: Docker Build and Push

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  packages: write # Required to push to GitHub Packages (GHCR)

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image_name: sgune/springboot_chat # Output the base image name
      sha_tag: ${{ steps.meta.outputs.version }} # Output the short SHA tag generated

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sgune/springboot_chat # Make sure this is your desired image name
          tags: |
            type=sha,prefix= # Tag with the short commit SHA (e.g., abcdef0)
            type=raw,value=test # Tag with 'test'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Assumes your Dockerfile is in the root of your repository
          file: ./Dockerfile # Specifies the Dockerfile name and location
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Enable build cache from GitHub Actions cache
          cache-to: type=gha,mode=max # Enable build cache to GitHub Actions cache

  tag-and-push-latest:
    runs-on: ubuntu-latest
    needs: build-and-push-image # Ensures this job runs after build-and-push-image
    if: github.ref == 'refs/heads/main' # Ensures this job only runs on pushes to the main branch
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io # This is Docker Hub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull, Tag and Push latest
        env:
          IMAGE_NAME: docker.io/sgune/chat-app
          SHA_TAG: latest
        run: |
          if [ -z "$IMAGE_NAME" ] || [ -z "$SHA_TAG" ]; then
            echo "Error: Image name or SHA tag not provided from the previous job."
            exit 1
          fi
          IMAGE_WITH_SHA_TAG="${IMAGE_NAME}:${SHA_TAG}"
          IMAGE_WITH_LATEST_TAG="${IMAGE_NAME}:latest"

          echo "Pulling image: ${IMAGE_WITH_SHA_TAG}"
          docker pull "${IMAGE_WITH_SHA_TAG}"

          echo "Tagging image ${IMAGE_WITH_SHA_TAG} as ${IMAGE_WITH_LATEST_TAG}"
          docker tag "${IMAGE_WITH_SHA_TAG}" "${IMAGE_WITH_LATEST_TAG}"

          echo "Pushing image: ${IMAGE_WITH_LATEST_TAG}"
          docker push "${IMAGE_WITH_LATEST_TAG}"