name: Docker Build and Push

on:
  push:
    branches:
      # - main # Adjust this if your default branch is different (e.g., master)
      - containerize

permissions:
  contents: read
  packages: write # Required to push to GitHub Packages (GHCR)

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sgune/springboot_chat
          tags: |
            type=sha # Tags with the commit SHA
            type=raw,value=latest,enable={{is_default_branch}} # Tags with 'latest' on the default branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Assumes your Dockerfile is in the root of your repository
          file: ./Dockerfile # Specifies the Dockerfile name and location
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Enable build cache from GitHub Actions cache
          cache-to: type=gha,mode=max # Enable build cache to GitHub Actions cache